// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtSEKOU-wfY7humBOzOSDoujCw_9S_bQI',
    appId: '1:406685101357:android:2c073a6f2bbd6b76f277a4',
    messagingSenderId: '406685101357',
    projectId: 'shopping-list-sample',
    storageBucket: 'shopping-list-sample.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1_vhZ24dCUgjqHbUovdaEGcRySllW_qc',
    appId: '1:406685101357:ios:50972d20ecea029cf277a4',
    messagingSenderId: '406685101357',
    projectId: 'shopping-list-sample',
    storageBucket: 'shopping-list-sample.appspot.com',
    iosClientId: '406685101357-ui5of079e918210p3hffqjd4vtua86j4.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingListSample',
  );
}
